### ISSUE TITLE
`pos` not being matched (always null)

### ISSUE THREAD

**Issue by fullofcaffeine** [elnabo/json2object#1]
Hey,

Tried playing a bit with the error handling, and it looks like  `pos` is always null:

http://try.haxe.org/#4FAa5

Output:

```
Main.hx:6: String,null
Main.hx:7: d,null
```

Am I doing something wrong?

**Comment by elnabo** [comment]
Your try haxe example, is not working. But an error, in the detection of error for single line json has been fixed with last commit.

haxelib package should be fixed later today.

**Comment by fullofcaffeine** [comment]
try haxe wasn't supposed to work (because try haxe doesn't support macros), but just a way to use it as a pastie :)

**Comment by fullofcaffeine** [comment]
Thanks!

**Comment by ibilon** [comment]
> try haxe wasn't supposed to work (because try haxe doesn't support macros), but just a way to use it as a pastie :)

Looks like try.haxe doesn't save code if it doesn't build, your link was empty ;)

**Comment by fullofcaffeine** [comment]
@ibilon Oh, apologies!
