### ISSUE TITLE
(default,null) typedef fields don't work

### ISSUE THREAD

**Issue by Gama11** [elnabo/json2object#11]
Trying to use json2object for vshaxe's build tool, I came across this issue:

![](http://i.imgur.com/F478HuO.png)

```haxe
class Main {
    static function main() {
        var parser = new json2object.JsonParser<ReadonlyStruct>();
        trace(parser.fromJson('{"foo":1}', ""));
    }
}

typedef ReadonlyStruct = {
    var foo(default,null):Int;
}
```

**Comment by ibilon** [comment]
Thanks for the report, fixed by https://github.com/elnabo/json2object/commit/7204b761f63ea3dc81c829f7d333fd97a5d425a6.

**Comment by Gama11** [comment]
Wow, that was quick! 👍
