### ISSUE TITLE
Abstract enum support

### ISSUE THREAD

**Issue by ibilon** [elnabo/json2object#12]
Give error when there's an invalid value.

- [x] Improve abstract enum support
- [x] Haxe inspired error messages

**Comment by elnabo** [comment]
Added support for String & Int abstract enum in 6fec696405f10cde918859fd909eba51854f8aed.

Other types wont be parsed.

**Comment by Gama11** [comment]
What about Float or Bool?

**Comment by elnabo** [comment]
Does a Bool abstract enum really make sense ?

As for Float I'm not sure if the comparison  of Float is the same on all target.

**Comment by Gama11** [comment]
I think it should be up to the user to decide what makes sense and what doesn't. :)

A `Bool` enum abstract can be useful to give different names to `true` / `false` (for API-design reasons for instance), while avoiding runtime-overhead. There's also use cases for "Bools with a third value", where one of the enum abstract values is `null`, and the underlying type is `Null<Bool>`.

**Comment by elnabo** [comment]
Hmm I see.

I'm going to try and support Bool enum. Not sure for Float yet.

**Comment by Gama11** [comment]
Also, seems like `Null<>` enum abstracts are overlooked in general - latest json2object doesn't work with vshaxe-build anymore:

>C:\HaxeToolkit\haxe\lib\json2object/git/src/json2object/DataBuilder.hx:265: characters 26-52 : json2object: Invalid enum abstract type should be String or Int

I don't even have any explicit `Null<>` types, just `@:optional` structure fields.

**Comment by elnabo** [comment]
Didn't expect that problem.
Since `@:optional` fields can be parsed a parser has to be made and here it can't.

In your case, is it an abstract enum type different than Float/Int/Bool/String or a Null of any the previous ?

**Comment by Gama11** [comment]
In this case it's just a simple `String` abstract, or technically `Null<String>` (because `@:optional` wraps types in `Null<T>`).

https://github.com/vshaxe/vshaxe-build/blob/master/api/vshaxeBuild/project/Project.hx#L62

**Comment by elnabo** [comment]
Yeah `Null` was ignored at the moment, forgot the behavior of `@:optional`, will try to fix it asap.

**Comment by Gama11** [comment]
No worries, not urgent. :)

**Comment by elnabo** [comment]
Ok so this should be fixed.

**Comment by Gama11** [comment]
Can confirm, vshaxe-build compiles again! :)

One minor issue: the error message for invalid enum abstract values is a bit confusing. It complains about the invalid value not being of type `String` here (rather than `HaxeTarget`, which is the name of the enum abstract):

![](http://i.imgur.com/mR1dOnL.png)

Perhaps the error message could even provide a list of valid values there.

**Comment by Gama11** [comment]
Also, I'd suggest putting the "variable parts" of the message into single quotes.

Compare:

>variable target should have been of type String

and

>variable 'target' should have been of type 'String'

In the second version, it's much clearer that "target" and "String" are not part of the error message itself.

**Comment by ibilon** [comment]
To do note: improve the error messages introduced in https://github.com/elnabo/json2object/commit/5fb22b67683825cbe2a3d6bad91296a1bec7c2a4

**Comment by elnabo** [comment]
Errors have been updated by 5fb22b67683825cbe2a3d6bad91296a1bec7c2a4, this include your first and last suggestion.

As for displaying the list of valid values, I think it's better to not surcharge the error message and to leave it to the doc.

**Comment by Gama11** [comment]
>As for displaying the list of valid values, I think it's better to not surcharge the error message and to leave it to the doc.

Fair enough. Depending on how many values an enum has, it could easily be too much text.
