### ISSUE TITLE
Generate shorter names

### ISSUE THREAD

**Issue by Gama11** [elnabo/json2object#18]
Haxe doesn't deal too well with the names json2object generates. Here's `-D dump=pretty` failing for instance:

![](http://i.imgur.com/nEIrrsy.png)

You can also see these names on hover:

![](http://i.imgur.com/OHtbiGH.png)

 Seems like this is more of an implementation detail that shouldn't surface? Anyway, it would already help if the generated names were not quite as long.

**Comment by Gama11** [comment]
I think this is also the reason why json2object sometimes breaks Neko. This code causes an error when trying to run the generated neko `.n`:

>Uncaught exception - load.c(398) : Invalid module : export/run.n

```haxe
class Main {
    static function main() {
        var parser = new json2object.JsonParser<Project>();
        trace(parser.fromJson('{}', "foo")); 
    }
}

typedef Project = {
    var a:Haxelib;
    var b:Target;
}

typedef Haxelib = {
    var c:String;
}

typedef Target = {
    >TargetArguments,
    var d:Bool;
    var e:String;
    var f:TargetArguments;
    var g:TargetArguments;
    var h:Bool;
    var i:Bool;
}

typedef TargetArguments = {
    var j:Array<String>;
    var k:Array<Array<String>>;
    var beforeBuildCommands:String;
    var afterBuildCommands:Array<Array<String>>;
}
```

I've reduced this a bit, so any simple changes seem to make the problem go away (try replacing `beforeBuildCommands` with a single-letter identifier for instance, or remove the `>TargetArguments` inheritance.

**Comment by elnabo** [comment]
The class generated have now shorter names. Your example is now working for me.
