### ISSUE TITLE
Field name alias

### ISSUE THREAD

**Issue by ibilon** [elnabo/json2object#21]
JSON:
```json
{
    "public": true
}
```

currently can't be represented since public isn't a valid field name.

Proposition: adding a `@:alias` metadata

```haxe
typedef Object = {
    @:alias("public") isPublic : Bool
}
```

**Comment by Gama11** [comment]
Somehow the issue wasn't closed despite `Close #21`. I guess it must be case-sensitive, because `close` is on the list: https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues

**Comment by elnabo** [comment]
It only close issue, when the commit is pushed on the default (master) branch.

**Comment by Gama11** [comment]
Oh, of course. I missed that it's on a branch. :)

**Comment by elnabo** [comment]
It will only close issue, when the commit will be pushed on the default (master) branch.
