### ISSUE TITLE
Cannot read property 'file' of null

### ISSUE THREAD

**Issue by Gama11** [elnabo/json2object#23]
The haxe-formatter unit tests have started failing with the following error:

>Cannot read property 'file' of null
Called from file:///C:/HaxeToolkit/haxe/lib/json2object/git/src/json2object/DataBuilder.hx line 274
Called from file:///C:/HaxeToolkit/haxe/lib/json2object/git/src/json2object/DataBuilder.hx line 705
Called from file:///C:/HaxeToolkit/haxe/lib/json2object/git/src/json2object/DataBuilder.hx line 689
Called from file:///c:/Users/Jens/.vscode/extensions/vshaxe/server/formatter/test/haxeFormatter/TestMain.hx line 78
Called from file:///c:/Users/Jens/.vscode/extensions/vshaxe/server/formatter/test/haxeFormatter/TestMain.hx line 66
Called from file:///c:/Users/Jens/.vscode/extensions/vshaxe/server/formatter/test/haxeFormatter/TestMain.hx line 64
Called from haxeFormatter.TestMain (file:///c:/Users/Jens/.vscode/extensions/vshaxe/server/formatter/test/haxeFormatter/TestMain.hx line 53)
Called from file:///c:/Users/Jens/.vscode/extensions/vshaxe/server/formatter/test/haxeFormatter/TestMain.hx line 39
Called from file:///C:/HaxeToolkit/haxe/lib/jstack/2,3,1/src/jstack/js/JStack.hx line 74
Called from file:///C:/HaxeToolkit/haxe/lib/jstack/2,3,1/src/jstack/js/JStack.hx line 120

I bisected this to 26015a3 (working fine one commit earlier).

**Comment by elnabo** [comment]
I didn't find a .hxml on the repo. How can I run the tests?

**Comment by Gama11** [comment]
Right.. it uses [vshaxe-build](https://github.com/vshaxe/vshaxe-build). I'll try to make an isolated example.

**Comment by elnabo** [comment]
It might be fixed by 87124f108f69403bba3619849a99fae88b200135.

**Comment by Gama11** [comment]
Indeed, thanks!
