### ISSUE TITLE
Haxe 4 / dev branch support

### ISSUE THREAD

**Issue by Gama11** [elnabo/json2object#26]
Because of https://github.com/HaxeFoundation/haxe/pull/6380, json2object needs an update to support Haxe 4. Ideally, the `haxe_ver` defines is checked ([example](https://github.com/HaxeFlixel/flixel/blob/dev/flixel/system/macros/FlxDefines.hx#L69)) to support both Haxe 4+ and 3.4.

![](http://i.imgur.com/NWZUG2y.png)

**Comment by ibilon** [comment]
Tried in https://github.com/elnabo/json2object/commit/07e52e08d73cbd85f35deb6f0097aac13db5d520, it fixes the issue but I'm seeing some inconsistencies in the tests on different targets.
Some say `null should 0` or `null should be []` but not all.

Also is the `haxe_ver` check necessary? There's either the null abstract or null typedef, so there shouldn't be any conflict in checking both.

**Comment by Gama11** [comment]
Hm, right, might not be necessary.

**Comment by ibilon** [comment]
Done in https://github.com/elnabo/json2object/commit/6d0c25e6855cb05a32e31ccd3b336bf062d145eb

**Comment by Gama11** [comment]
Hm, something seems to be broken.. will look into it later. https://travis-ci.org/vshaxe/vshaxe#L677

**Comment by Gama11** [comment]
Nvm, that was actually an issue with the macros in haxe-formatter, which also needed an update.
