### ISSUE TITLE
empty constructor requirement for classes

### ISSUE THREAD

**Issue by nadako** [elnabo/json2object#29]
It seems a bit unfortunate that to deserialize a class instance, a public empty constructor is required, especially considering that Haxe doesn't support (constructor) overloading.

How about using `Type.createEmptyInstance` instead? I believe this method was specifically added for deserializers so one can easily create an unitialized instance to fill fields later.

**Comment by ibilon** [comment]
Make sense.
I also found this an issue, well annoying, when doing a data only class and you have to add a constructor which does nothing.

Can `final` fields be set by reflection? Right now the lib assume the constructor will set it.

**Comment by ibilon** [comment]
The library doesn't require a constructor anymore.

As a side effect code like this:
```haxe
class T {
  public var v : Int = 4;
}
```
doesn't affect the result of the parsing.
If the default value is needed in case the variable is missing from the json `@:default` should be used:
```haxe
class T {
  @:default(4) public var v : Int;
}
```
