### ISSUE TITLE
expose types for json generated

### ISSUE THREAD

**Issue by francescoagati** [elnabo/json2object#39]
hi,
there is a possibility for have also the types generated for the json? in this mode we can have the possibility of expose this types also in jsonschema or in typescript.

**Comment by elnabo** [comment]
You mean to generate a json-schema with respect to a type.

I.e. something like ```new JsonSchemaBuilder<Type>().generate()```

**Comment by Gama11** [comment]
For JSON schemas, you might want to look at https://github.com/nadako/haxe-type-to-json-schema.

**Comment by francescoagati** [comment]
yes but that can generate a schema in haxe types. so i can expose the schema in typescript for example

**Comment by elnabo** [comment]
We could generate a json-schema (json format), but enums with constructor would prevent to generate Haxe typedef from it.

**Comment by francescoagati** [comment]
But enum with constructors are converted in normal object json

**Comment by elnabo** [comment]
Enums with constructor can be supported in json-schema thank to unions. 

For example, the enum
```haxe
enum Color {
    RGB(r:Int, g:Int, b:Int);
    HSV(h:Float, s:Float, v:Float);
}
```

would be considered in json as the union of the two enum constructor

`type Color = type RGB or type HSV`

However, as far as i know if you want to support type union in Haxe, the solution seems to be `haxe.ds.Either` which is an enum with constructors and will induce a large complexification of the types.

**Comment by francescoagati** [comment]
```
enum Color {
  Red;
  Green;
  Blue;
  Rgb(r:Int, g:Int, b:Int);
}
```
can be converted in 
```
typedef Color = {
  Red:{},
  Green:{},
  Blue:{},
  Rgb:{r:Int, g:Int, b:Int}
}
```

**Comment by elnabo** [comment]
They are different types. The json we generate doesn't match these transformations.

**Comment by elnabo** [comment]
A branch has been created. It features a macro to generate a `json-schema` from a given type.

You can use it with `json2object.utils.JsonSchemaWriter`

I.E. `new JsonSchemaWriter<json2object.Position>().schema`.

It is highly experimental until I find a good way to test it efficiently.

**Comment by elnabo** [comment]
The experimental schema writer is now available in j2o 3.5.0

**Comment by Gama11** [comment]
It looks like there's some traces leftover in `DataBuilder`, my output channel is getting spammed during completion in VSCode. ;)

**Comment by francescoagati** [comment]
really thanks i will try to use it
