### ISSUE TITLE
Doc comment descriptions for schema generation 

### ISSUE THREAD

**Issue by Gama11** [elnabo/json2object#40]
It would be nice if generated JSON schemas included the doc comments of fields in the `"description"` property ([example](https://github.com/vshaxe/vshaxe-build/blob/master/schemas/vshaxe-build-schema.json#L47)). This allows for nice auto-completion and hover hints in VSCode:

![](https://i.imgur.com/N70vsoA.png)

```haxe
typedef Project = {
	/** The name of the project **/
	final name:String;
}
```

**Comment by elnabo** [comment]
This has been added in d1585f574d37397c516414569b6c43d34a20a7aa.

**Comment by elnabo** [comment]
The documentation of `Enum` fields with constructor without parameters and of `@:enum Abstract` is however ignored due to their representation as `enum` in the schema.

**Comment by Gama11** [comment]
I think JSON schemas support that via `enumDescriptions`: https://github.com/vshaxe/vshaxe/blob/master/package.json#L363

**Comment by elnabo** [comment]
Oh, didn't see that, will add it then.

**Comment by elnabo** [comment]
`enumDescriptions` isn't in the spec but I use an alternative syntax to add the `description` for fields of `Enum` and `@:enum Abstract` in 9aab2dad12d77318dc07abcba94cf7abf389b2eb.

**Comment by Gama11** [comment]
Hm, maybe that's just VSCode's flavor of JSON schemas then. What do you mean by alternative?

**Comment by elnabo** [comment]
All values types of the Enum are listed in a large `anyOf` array. 

Values previously stored in a `enum` are in the `anyOf` array declared as `{"const": value}` with an optional `description`.

**Comment by Gama11** [comment]
Seems to work fine for VSCode's schema completion. 👍
