### ISSUE TITLE
Invalid schema generated with @:optional

### ISSUE THREAD

**Issue by Gama11** [elnabo/json2object#42]
```haxe
typedef Project = {
	@:optional final name:String;
}
```

The schema generated for the above includes `name` in the `required` array even though it's optional.

**Comment by elnabo** [comment]
This one is weird, when I generate a schema for this type. The `required` array is absent.

Which Haxe version did  you use ?

**Comment by Gama11** [comment]
Hm, you're right, I may have made a mistake while testing this. :)

There still seems to be an issue here, the generated json isn't valid if it's missing the `required` array:

![](https://i.imgur.com/sbDDWDC.png)

**Comment by elnabo** [comment]
This one should be fixed by  7ad20669c5a609931d08905a807e3d117488ba0b
