### ISSUE TITLE
Schema generator breaks completion

### ISSUE THREAD

**Issue by Gama11** [elnabo/json2object#44]
Getting this error during code completion:

>json2object/utils/schema/DataBuilder.hx:271: characters 4-9 : Uncaught exception Abstract vshaxeBuild.project.ArrayHandle<vshaxeBuild.project.Target> has no json representation #pos(src/vshaxeBuild/tools/SchemaGenerator.hx:9: characters 20-45)

This seems to be exlusive to display mode, it generates the schema fine.

**Comment by elnabo** [comment]
Well for the moment I've disabled the generation of the schema in display mode.

No idea, why this breaks things.

**Comment by Gama11** [comment]
Hm, too bad, it was kinda neat that you could see the generated schema on hover. :)

![](https://i.imgur.com/W60IdU5.png)

I guess that doesn't really have much practical use though.

**Comment by elnabo** [comment]
Yeah I don't untersand how that works.

I disabled the generation in the display mode as per suggestion of ibilon. But when I put it back to try and debug, it worked fine. 

And now I'm trying my harderst to make it crash again, fss.

**Comment by elnabo** [comment]
Ok, so for some reason, sometimes in display mode Haxe doesn't keep the expression of abstract enum fields. And thus crash happens.
