### ISSUE TITLE
Schema generator should strip indentation from doc comments

### ISSUE THREAD

**Issue by Gama11** [elnabo/json2object#46]
Ran into this issue while trying to use the schema generator for haxe-formatter's `hxformat.json`:

```haxe
typedef FormatterConfig = {
	/**
		turns off formatting for all files in current folder and subfolders
		unless subfolder contains a "hxformat.json"
	**/
	@:default(false) @:optional var disableFormatting:Bool;
}
```

The generated description includes the indentation and newlines, which makes it look strange in completion / hover:

![](https://i.imgur.com/5zt9Fnc.png)

Might start to get a bit tricky if you need to handle JavaDoc style doc comments as well, there you have to consider the leading `*`..

![](https://i.imgur.com/WKdUYh9.png)

**Comment by elnabo** [comment]
I added a little doc cleaner in 98a52d0f2815e83000346ac7b03d1179f0dff42d.

It follows classic rules for newlines: a single newline is ignored, a pair of newline is transformed into a new line.

For `*`, they are kept at line start if and only if all non empty lines are starting with a `*`.

**Comment by Gama11** [comment]
Looks good to me, thanks! :)

![](https://i.imgur.com/L2TmL9t.png)
