### ISSUE TITLE
"No parser can be generated for" error should have a position

### ISSUE THREAD

**Issue by Gama11** [elnabo/json2object#48]
The "No parser can be generated for" error currently doesn't show up in VSCode diagnostics because it doesn't have a position. It can also make it hard to find out where the error originates in a regular compilation.

Couldn't this point to the place where the `JsonParser` is constructed, or even the appropriate type parameter?

```haxe
import json2object.JsonParser;
import haxe.DynamicAccess;

class TableGenerator {
	static function main() {
		var parser = new JsonParser<Map<String, DynamicAccess<Float>>>();
	}
}
```

>json2object: No parser can be generated for haxe.DynamicAccess<Float> as it has no supported @:from

**Comment by elnabo** [comment]
I think, it's better to point to the construction of the JsonParser, as it is at least inform where the problematic part.

**Comment by Gama11** [comment]
Yeah, I meant the type parameter position where it's constructed. But you probably can't get that position.
