### ISSUE TITLE
Problems with nested structures that have final fields

### ISSUE THREAD

**Issue by Gama11** [elnabo/json2object#49]
This is fine:

```haxe
class Main {
	static function main() {
		var parser = new json2object.JsonParser<Data>();
	}
}

typedef Data = {
	final foo:String;
	final bar:{
		var foobar:String;
	}
}
```

However, if the inner field in `Data` is made `final` as well, the following error happens with latest Haxe and json2object:

```
DataBuilder.hx:267: characters 53-133 : error: Cannot unify final and non-final fields
DataBuilder.hx:267: characters 53-133 :  have: { foobar: Dynamic }
DataBuilder.hx:267: characters 53-133 :  want: { foobar: Dynamic }
DataBuilder.hx:791: lines 791-863 : Defined in this class
```

**Comment by elnabo** [comment]
I think this is an Haxe bug, when we convert the inner type to a complex type using `TypeTools.toComplexType` the information about `final` is lost.

**Comment by Gama11** [comment]
Hm... in that case, somebody should isolate it and report a Haxe issue. Not sure I'm familiar enough with json2object internals though.

**Comment by elnabo** [comment]
I've planned to try to do it this week-end.

**Comment by ibilon** [comment]
Fixed by https://github.com/elnabo/json2object/commit/78672d0175fc6e3b60bb5b5b9d601b12009a763b.
