### ISSUE TITLE
Schema writer escaping regressions

### ISSUE THREAD

**Issue by Gama11** [elnabo/json2object#55]
I noticed two regressions when re-generating `hxformat-schema.json` with latest json2object:

- every string value now seems to have escaped quotes (?)

    ![](https://i.imgur.com/JEMh3Ua.png)

- newlines in doc comments are escaped now, and they're surrounded by escaped quotes as well

    ![](https://i.imgur.com/r0FrKYR.png)

**Comment by elnabo** [comment]
My bad, forgot to remove the quoting when I rewrote JsonSchemaWriter. Should be fixed by 6ed8408c72cd093cc9e99fcd54e5a0741cb15ade.

An haxelib release should follow soon.
