### ISSUE TITLE
More markdown whitespace issues

### ISSUE THREAD

**Issue by Gama11** [elnabo/json2object#63]
`VSCodeSchemaWriter` generates the following for [this type](https://github.com/lix-pm/haxeshim/blob/master/src/haxeshim/LibResolution.hx):

```
"markdownEnumDescriptions": [
	"\n    Any parameters that are passed to haxeshim are parsed, including hxmls and the `-lib` parameters are \"intercepted\".\n    To resolve these, we look for a `haxe_libraries/<libName>.hxml` and parse the parameters there
	"\n    Parameters are still parsed and then passed to `haxelib path` for resolution.\n    In this case `-lib name:version` syntax is allowed.\n  ",
	"\n    This is a mix of both approaches. Libraries that are not found using scoped\n    resolutio nor that use `-lib name:version` format are process with `haxelib path`.\n  "
]
```

It looks like the leading whitespace leads to the content being considered as a code block, since a monospace font is used in completion and backticks aren't rendered:

![](https://i.imgur.com/AOxB1yP.png)

If I remove the leading whitespace manually, it works as expected.

There's also some redundant trailing whitespace in those descriptions, but that shouldn't break anything.

**Comment by Gama11** [comment]
Hm.. there's still a leading `\n` that doesn't seem correct, but that doesn't break anything. :)

**Comment by elnabo** [comment]
With last commits extra new lines at the start/end of the descr are removed
