### ISSUE TITLE
TypeUtils.copyType Error in Haxe 4.2

### ISSUE THREAD

**Issue by 0xA3** [elnabo/json2object#72]
TypeUtils.hx:70: lines 70-92 : Object requires field isAbstract

In my local copy of the lib I added this in line 75 of TypeUtils.hx which resolves the error
#if (haxe_ver >= 4.2) isAbstract: false, #end

**Comment by elnabo** [comment]
Thanks for the reminder, it was fixed by #71 but not released on Haxelib.

It should now be available as version 3.9.0
