### ISSUE TITLE
Type not found : ListNode

### ISSUE THREAD

**Issue by araneta** [elnabo/json2object#75]
I got this error when building my project
haxe build.hxml 
Type not found : ListNode
/home/aldo/haxelib/json2object/3,9,0/src/json2object/writer/DataBuilder.hx:381: lines 381-405 : Defined in this class
what should i do?

**Comment by ibilon** [comment]
The error line isn't enough to figure out what's going on.
Are you using a `@:default` metadata? That's the most likely source of type not found.
You'd need to share some code to figure this out.

**Comment by araneta** [comment]
I'm sorry i forgot to put the code, here is the code that cause the error

 ```
 var writer = new JsonWriter<List<rest.entities.Telo1>>(); // Creating a writer for Cls class
    var json = writer.write(x);
```

and here the class

package rest.entities;
```

class Telo1{
	public var ID:Int;
	public var Name:String;
	
	public function new (){
	}
}

```
I'm newbie in haxe so please help me.
Thanks

**Comment by elnabo** [comment]
Are you targeting neko ?

**Comment by araneta** [comment]
php

**Comment by elnabo** [comment]
Ok, I see the problem.

We'll have to add a special case to the conversion to use a json array to represent the List.

In the meanwhile, for writing purpose only, you could convert your List to an Array.

**Comment by araneta** [comment]
thanks its working

**Comment by elnabo** [comment]
For information since version 3.10.0 the List type is directly supported.

**Comment by araneta** [comment]
ok great thanks
