### ISSUE TITLE
feature request haxe.ds.Either support

### ISSUE THREAD

**Issue by lublak** [elnabo/json2object#79]
Sometimes an array can contain multiple types. It would be useful to support haxe.ds.Either.
(also nested Either)

**Comment by elnabo** [comment]
Hello.

`haxe.ds.Either` is simply an enum and thus it is already supported by json2object with something like `{"Left": {"v": "foo"}}`.

For what you wish I would advise to use abstract or a custom parser for the field.

**Comment by tokiop** [comment]
Hi @elnabo thanks for the pointers ! I'm having the same issue, and a hard time figuring it out. Been looking at the Abstract tests and reading the docs, but don't manage to make it work.

Would you have an example of how to implement and read/write a mixed array using abstract (or other mean) ?

**Comment by elnabo** [comment]
Hello.

 ### Abstract

For writing: json2object will generate using the base type

For reading: the behavior is a bit complex. There can be up to 5 supported type (string, boolean, number, array and object) using the `@:from notation` (https://haxe.org/manual/types-abstract-implicit-casts.html)

Maybe the **Taking it further with abstract types** from https://code.haxe.org/category/other/passing-different-types-to-a-function-parameter.html may be what you want

### Custom parser

With Custom parser/writer you have full control for example if you want to read an  `Array<Either<String, Int>>` from `[1, 2, "three"]` you can use something like this function (there might some error as I didn't test it)

```haxe
public static function customParse(val:Json, name:String):Array<Either<String, Int>> {
	return switch (val.value) {
		case JArray(values):
			var res = [];
			for (v in values) {
				switch(v.value) {
					case JNumber(s):
						res.add(Right(Std.parseInt(s));
					case JString(s):
						res.add(Left(s));
					default:
						continue;
				}
			}
			return res;
		default:
			null;

	}
}
```

**Comment by tokiop** [comment]
Thanks for your quick reply, will look into it again !

**Comment by lublak** [comment]
@elnabo thank you :) yes okay. I can do it. I close this issue now.
