### ISSUE TITLE
Problems with Visual Studio haxe language server

### ISSUE THREAD

**Issue by Pidroh** [elnabo/json2object#83]
My project builds fine but the haxe language server doesn't work.
```
Type not found : json2object.JsonWriter
```
This results in auto-complete being disabled for my code base :(

**Comment by ibilon** [comment]
Does `import json2object.Position;` work? If not this should be an issue with your setup.
Can you include your hxml?

**Comment by Pidroh** [comment]
oh god :( you are right, the haxe project was using another hxml in the project for the language server, not the one I was using to build the project, sorry for the trouble and thanks for pointing me in the right direction!
