### ISSUE TITLE
Compilation server: JsonWriter_0 is redefined from module JsonWriter_0

### ISSUE THREAD

**Issue by ianharrigan** [elnabo/json2object#87]
When using json2object (v3.10.0) the following is seen when enabling the haxe compilation server in vscode (which is the default setting)
```
DataBuilder.hx:381: lines 381-405 : Type name JsonWriter_0 is redefined from module JsonWriter_0
```
Any thoughts on what this might be or how to resolve it? Note that when disabling the compilation server, everything is fine.

Thanks for the great lib!

**Comment by elnabo** [comment]
This is an issue that is caused by multiple generation of the parser/writer in a single compilation server session.

The latest version (3.11.0) should no longer have this issue thanks to #85

**Comment by ianharrigan** [comment]
Follow up: it seems the git version of this lib works with compilation server, though not sure how well just yet. However, have you considered making a release since its certainly in a better state than the current haxelib version

**Comment by ianharrigan** [comment]
Oh, ignore me completely, i hadnt released there _had_ been a release recently!
