### ISSUE TITLE
json2object: Parser of Dynamic are not generated 

### ISSUE THREAD

**Issue by charlesisfeline** [elnabo/json2object#97]
no this isnt a duplicate, this issue is in a different line

![image](https://github.com/elnabo/json2object/assets/62410083/a110a7ba-cae4-4279-a041-08040b588dfa)

dont mind the questionable font choice, just thought it was funny

**Comment by elnabo** [comment]
Hello, some of your data is containing Dynamic types.

To be able to parse them you'll need to use customer parser with `@:jcustomparse`

There is an example in the README

**Comment by charlesisfeline** [comment]
![image](https://github.com/elnabo/json2object/assets/62410083/eea944b7-4223-4e7d-bed0-fcf531d40d5a)

![image](https://github.com/elnabo/json2object/assets/62410083/6be13940-23a7-40c3-a45f-477435ae2dd5)

still the same
